[link text](https://)

In [3]:
#20MAI0011
#ATHIRA SREEKUMAR
#Creating Input matrix
import numpy as np


In [1]:

values = ([2,3],[5,6],[8,9])
print("Training input values without Bias\n", values)


Training input values without Bias
 ([2, 3], [5, 6], [8, 9])


In [4]:
#Adding Bias to the input values
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training input values with bias in it\n",values)


Training input values with bias in it
 [[-1  2  3]
 [-1  5  6]
 [-1  8  9]]


In [5]:
#Creating random weights
m=3     #number of elements in each row of inputs
n=1 
weights = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",weights)


Initial random weights
 [[-0.47608154]
 [-0.47726144]
 [-0.48841929]]


In [6]:

#Target values Matrix
final = ([0],[1],[1])
print("Training data target values are\n", final)


Training data target values are
 ([0], [1], [1])


In [7]:
#Method for updating weights
def updateWeights(weights, inputs, activation, targets):
    eta = 0.25
    weights += eta*np.dot(np.transpose(inputs), targets - activation)
    return weights


In [8]:
#Creating Methods for Learning
def  prediction (inputs, weights, targets):
    #representing Activation function with 'ack [[]]' variable
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(weights)):
            ack[i] += inputs[i][j] * weights[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        #checking values with target
        if(targets[i] != ack[i]):
            weights = updateWeights(weights, inputs, ack[i], targets)
        print(ack[i])
    return weights


In [9]:
#Training our model and extracting stable weights
iterations = 4
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    weights = prediction(values, weights, final)
    
print("\nTrained Weights\n", weights)



Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Trained Weights
 [[-0.22608154]
 [ 1.27273856]
 [ 1.01158071]]


In [11]:
def perceptronPredict(weights, newInput):
    activation = np.dot(newInput, weights)
    activation = np.where(activation>0, 1, 0)
    print(activation)

In [12]:
newInput = ([-1.0, 7,8])
perceptronPredict(weights, newInput)

[1]
